// define a variable to import the <Verifier> or <renamedVerifier> solidity contract generated by Zokrates

const Verifier = artifacts.require('Verifier');
// Test verification with correct proof
// - use the contents from proof.json generated from zokrates steps
const proofs = require('./proofs');


    
// Test verification with incorrect proof
contract('Verifier', accounts => {
    beforeEach(async () => {
        this.contract = await Verifier.new({
            from: accounts[0]
        });
    });
});